### ISSUE TITLE
DFS & wwDotNetBridge: Method 'System.DBNull.BrowserSubprocessPath' not found...

### ISSUE THREAD

**Issue by dsdsdfsdfsfsdfsfsdf** [cwollenhaupt/fpCefSharp#26]
An error occurs when setting the path for the BrowserSubprocessPath property:
OLE IDispatch exception code 0 from wwDotNetBridge: Method 'System.DBNull.BrowserSubprocessPath' not found...
I want to use a DFS (Distributed File System) path eg: \\TEST.LOCAL\DFS$\CEFSHARP$ and an error occurs when setting in wwDotNetBridge.SetProperty().
How should I correctly write the path for DFS (Distributed File System)?
Thanks.

**Comment by cwollenhaupt** [comment]
Can you post the actual code you are using or point to the line in fpCefSharp that is causing the error.

**Comment by dsdsdfsdfsfsdfsfsdf** [comment]
This is my procedure:

	Procedure CheckDpiAwareness (toBridge, toSettings)
		LOCAL lnIsProcessDPIAware
		*--------------------------------------------------------------------------------------
		* If this process is DPI aware, we use the default
		*--------------------------------------------------------------------------------------

		DECLARE long IsProcessDPIAware IN Win32Api AS IsProcessDPIAware_brws
		lnIsProcessDPIAware = IsProcessDPIAware_brws()
		CLEAR DLLS "IsProcessDPIAware_brws"

		If !EMPTY(lnIsProcessDPIAware)
			Return
		EndIf
		
		*--------------------------------------------------------------------------------------
		* If we don't have a DPI unware sub process, we can't do anything either. This could
		* happen when older releases of CefSharp are mixed with later releases of fpCefSharp.
		*--------------------------------------------------------------------------------------
		Local lcPath, lcExe
		lcPath = This.GetCefSharpPath ()
		lcExe = Addbs (m.lcPath) + "CefSharp.BrowserSubprocess.dpiunaware.exe"
		If Empty (Sys (2000, m.lcExe))
			Return
		EndIf
		
		*--------------------------------------------------------------------------------------
		* Otherwise we use the DPI unaware process.
		*--------------------------------------------------------------------------------------
		toBridge.SetProperty (m.toSettings, "BrowserSubprocessPath", m.lcExe)   && **the error is on this line**
	ENDPROC

**Comment by dsdsdfsdfsfsdfsfsdf** [comment]
I have a question, does chromium support running cefsharp libraries from a DFS server?

**Comment by cwollenhaupt** [comment]
DFS path: CefSharp uses the BrowserSubprocessPath property to locate the EXE and launches it using regular Windows API functions. Anything that you could put after the RUN command in VFP and anything that can be read with FILETOSTR() would work here. There's no code to specifically handle DFS (or any other file system). The browser relies on being able to use file functions.

I noticed that the code you posted is different from the original. Was there a problem that you were solving with this change that I should be aware of?

As I mentioned elsewhere I don't think the error is the value of this property, but something while loading the CefSharp library. I'm happy to look at this, if you can provide me with a small test program that I can quickly run from my development folder. Please make sure you are testing with the latest release and the original CefSharpBrowser.prg.

I fixed one bug in the loading process in v97.1.16.3 which should be available later today. You might want to wait for this version before creating the repro code.

**Comment by dsdsdfsdfsfsdfsfsdf** [comment]
I use modified cefsharpbrowser.prg from version v197.1.61. Due to initial problems with the application in our application SW, I had to make modifications/corrections - e.g. downloading files in cefsharp or opening/closing subprocesses, modifying the display of subtitles (Caption), error return values and others... My modified cefsharpbrowser.prg also contains some of your modifications in versions v197.1.61.1,2,3. But I'm still using the original DLL libraries from version v197.1.61, because I have a problem reinstalling the new DLL libraries modified by you en masse. Our SW where chromium is used, is used by many PC clients - about hundreds.

**Comment by dsdsdfsdfsfsdfsfsdf** [comment]
I have error in cefsharpbrowser.prg - line loBridge.LoadAssembly("\\\test.local\dfs$\myApp\chromium\cefsharp.dll") 
-> loBridge.LoadAssemblyFrom("\\\test.local\dfs$\myApp\chromium\cefsharp.dll"):

An attempt was made to load an assembly from a network location which would have caused the assembly to be sandboxed in previous versions of the .NET Framework. This release of the .NET Framework does not enable CAS policy by default, so this load may be dangerous. If this load is not intended to sandbox the assembly, please enable the loadFromRemoteSources switch. 
See http://go.microsoft.com/fwlink/?LinkId=155569 for more information.
\\\test.local\dfs$\myApp\chromium\cefsharp.dll

How to fix this error?
Thanks.

**Comment by cwollenhaupt** [comment]
You need to create a configuration file for your application (myApp.exe.config) and add the key that is documented in the link you posted. Please note that when you run this in VFP for debugging purposes, you have to create a VFP9.exe.config with these settings in the same folder as VFP9.exe, because VFP is the executing process, not myApp.exe.

A minimum config file looks like this:

```
<configuration>
    <runtime>
       <loadFromRemoteSources enabled="true"/>
   </runtime>
</configuration>
```

**Comment by dsdsdfsdfsfsdfsfsdf** [comment]
I have prepared a file for my myApp.exe file (program).
myApp.exe.config with this content:

``` 
<?xml version="1.0" encoding="UTF-8"?>
<configuration>
   <runtime>
      <loadFromRemoteSources enabled="true"/>
   </runtime>
</configuration>
```

myApp.exe no longer shows any errors.
Thanks for Your time.
