### ISSUE TITLE
installation problem - fpDotNet folder not find

### ISSUE THREAD

**Issue by ilrisa** [cwollenhaupt/fpCefSharp#9]
Hi,
I'm trying to install following the instructions, but I can't find the fpDotNet directory that contains the COMs to register.
I don't even find them in the original fpDotNet project ... what am I wrong?

Thanks

**Comment by cwollenhaupt** [comment]
Are you looking at the repository or the release? It's part of the ZIP file that you can download on the [release page](https://github.com/cwollenhaupt/fpCefSharp/releases/tag/v92.0.260). The content of the ZIP file looks like this:

![image](https://user-images.githubusercontent.com/33864363/133249678-df650c3d-0230-4060-b052-d7d83324c835.png)

The second folder is fpDotNet with the ActiveX control to host the web browser.

**Comment by cwollenhaupt** [comment]
The fpDotNot repository is [here](https://github.com/cwollenhaupt/fpDotNet), but it, too, only contains the source code, not the binaries.

**Comment by ilrisa** [comment]
thanks, my mistake
